### ISSUE TITLE
Not working with the TAB-based indentations

### ISSUE THREAD

**Issue by angelside** [GabrielGod1/indent-rainbow-blocks#1]
Hi,

It looks like it's not working as intended with the TAB-based indentations, which in **GoLang** we use for tab-based indents.

*Windows 10*
*Vscode 1.81.1*

**Tab indentation**

![image](https://github.com/GabrielGod1/indent-rainbow-blocks/assets/7515/88ffe400-b59e-45f0-923f-199db68a45aa)

**Space indentation**

![image](https://github.com/GabrielGod1/indent-rainbow-blocks/assets/7515/98ac2c8c-1a82-4157-8d2c-a2f61606ffdd)

**Comment by GabrielGod1** [comment]
Hi,

Thank you for bringing this to my attention.

I understand the importance of proper TAB-based indentation and have begun testing it with GoLang. It appears the global issues you're encountering are common and replicable. This behavior could indicate the extension's interpretation of indentation might not be in perfect harmony with how Go —or VS Code's configuration for Go— handles indentation, particularly in the spaces vs tabs as you showed above.

I'll be dedicating time this week to see if I can integrate a solution into the extension. If I can pinpoint and fix the issue, you can expect an update soon.

Thanks for your patience and understanding!

**Comment by GabrielGod1** [comment]
@angelside 

I've rolled out a new update. The extension now manages indentation for tab-based languages independently. It adjusts to different tab sizes and works seamlessly with formatters such as "gofmt". Should you encounter any concerns, kindly let me know. I'll keep the GitHub issue open for about a week in case a new issue arises.

Regards,

**Comment by angelside** [comment]
Hey, seems ok.

![image](https://github.com/GabrielGod1/indent-rainbow-blocks/assets/7515/fae54632-c030-43e2-9bdb-4e8208f746a8)
