### ISSUE TITLE
dynamic indentation detection not working as expected

### ISSUE THREAD

**Issue by ITMonkey78** [GabrielGod1/indent-rainbow-blocks#2]
v0.0.2 Changelog - Added dynamic indentation detection: Recognizes changes made either in the settings or via the status bar in real time.

This doesnt seem to be working as described.

Amended the default black colour (rgba(0, 0, 0, 0.15) with white (rgba(255, 255, 255, 0.15) in the settings.json (for both User and Workspace areas) and returned to my open file and the colours were unchanged.

Tabbing content DOES show the indentation color but for the old setting.

Closing VS Code and reopening it shows the correct colours.

VS Code Version: 1.84.2

**Comment by GabrielGod1** [comment]
Changes to both the background colors and coloring style are not taking effect inmediately by saving the settings.json file. The updates are only applying after manually reloading the window or reopening VS Code as you mentioned. I'm working on an update to implement 'event listeners' for these changes, similar to what's already functioning for tab sizes configuration.

Thank you for bringing this to my attention. Once I finalize the solution and ensure it is manageable while maintaining the performance of the extension, I'll be pushing a new update soon.

**Comment by GabrielGod1** [comment]
@ITMonkey78 

Thanks for your patience, I've rolled out a new update (v0.0.3). Now, changes to both background colors and coloring styles should take effect immediately without the need to manually reload VS Code. I've also introduced the Color Palettes Tool, easily accessible by clicking the color palette symbol in the bottom right corner of the VS Code screen (status bar). This tool allows you to create, test, view, update, and save any color palette through an intuitive interface. If you encounter any further issues or have additional suggestions, please feel free to let me know.

Regards,
